### ISSUE TITLE
Failure mode when emojis.js can't be loaded

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1752]
Relates to cf94a2c02f6c23e34ec8b0a0982c55cf93d406fd

If the `emojis.js` file can't be loaded (some kind of webpack chunked loading setup?), Converse appears to load normally but then behaves completely FUBAR: all chat windows remain empty no matter how much you or other users type.

On pageload, there will be a webpack error message regarding module loading.

To reproduce, remove `dist/emojis.js` from your checkout; or use e.g. https://inverse.chat/ and create a uBlock rule for `https://cdn.conversejs.org/5.0.4/dist/emojis.js`.

**Comment by jcbrand** [comment]
Duplicate of  #1751.

**Comment by laszlovl** [comment]
I meant for this ticket to exist even though the CDN builds have been fixed by now.

If for some reason in the future (an overactive adblocker; a network error; someone running a self-hosted build who forgot to copy `emojis.js`; etc) the `emojis.js` file can't be loaded, I think it would be very useful if Converse either failed with a hard error immediately or handled it gracefully by simply skipping emojis. The current failure mode where Converse appears to function normally but then does't display any chat messages at all is very confusing.

**Comment by jcbrand** [comment]
Ok sorry.

**Comment by jbg** [comment]
Additionally the `/dist/emojis.js` relative path seems to be hard-coded, making it more likely that this bug will be encountered. I am bundling Converse into a larger app and just hit this very confusing bug.

**Comment by jbg** [comment]
I just found `assets_path`, which works nicely. This bug remains quite confusing though - the behaviour I saw (no messages appearing at all) is not obviously related to failure to load some emojis.

**Comment by juancar0505** [comment]
I can't open the emojis when I build the project. I don't know if it's a bugg. When I use the cdn, I can open them perfectly, but if I try to build my project and use the local files (dist/converse.js, dist/converse.css) I can't open them.

**Comment by codecleric** [comment]
Holy Crap.

I was trying to embed conversejs into a docker swarm mode based web application using external auth on the ejabberd side. So, lot's of layers. 

Everything was going swimmingly, you could log into converse, add contacts, get presence updates... just never send any chat or muc messages, and yes - the emojis error was happening. 

After a week of troubleshooting and building stripped down environments, we determined exactly what this issue is about, and then I found this issue :-)

Not a good way to throw the error, so I agree it should be handled differently. I will try to do a pull request in the next couple of months, but I have to learn this codebase first!

**Comment by TheEletricboy** [comment]
I fixed the issue in a React Environment using vite as a bundler. Check this comment: https://github.com/conversejs/converse.js/issues/1751#issuecomment-2459615368
